#\u914D\u7F6E\u6570\u636E\u5E93\u7684\u8FDE\u63A5\u4FE1\u606F
spring:
  application:
    name: ems
    #\u6570\u636E\u5E93\u7684\u8FDE\u63A5\u4FE1\u606F
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 111111
  servlet:
    multipart:
      #\u6700\u5927\u5355\u4E2A\u6587\u4EF6\u5927\u5C0F
      max-file-size: 10MB
      #\u6700\u5927\u8BF7\u6C42\u5927\u5C0F
      max-request-size: 100MB
#Mybatis\u7684\u76F8\u5173\u914D\u7F6E -- \u5C06Mybatis\u7684\u65E5\u5FD7\u8F93\u51FA\u5230\u63A7\u5236\u53F0,\u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u89C4\u5219\u6620\u5C04
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # \u5F00\u542F\u9A7C\u5CF0\u6620\u5C04\u660E\u547D\u540D\u5F00\u5173
    map-underscore-to-camel-case: true
#\u914D\u7F6E\u4E8B\u52A1\u7BA1\u7406\u65E5\u5FD7\u7EA7\u522B
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug
#\u963F\u91CC\u4E91OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-spring-web-learn
    region: cn-beijing
server:
  address: 127.0.0.1
  port: 8080